# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sunfish/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sunfish)

$(call add-radio-file-sha1-checked,radio/abl.img,c9c3b0a8ad0d1ba9da5208bd68e98ec790e48341)
$(call add-radio-file-sha1-checked,radio/aop.img,3e90992daa4dccbf2f7c3fd96316772210eadbfe)
$(call add-radio-file-sha1-checked,radio/devcfg.img,9f815d4a5ca3c2478370fb8fdaf76610547a5d96)
$(call add-radio-file-sha1-checked,radio/hyp.img,8fd4bc1d9250281bf72bbf2811fa45c1eeb60dc1)
$(call add-radio-file-sha1-checked,radio/keymaster.img,47dbb68438d7247c620a6031acfb6e5e1434da38)
$(call add-radio-file-sha1-checked,radio/modem.img,f02c5986274cffc348cdf6b91c1bad26583441e6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3277904e619487d05b385043099e83ccc828aa30)
$(call add-radio-file-sha1-checked,radio/tz.img,4079e9ea93ffc87bc62147a8164f878b73cf3684)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,f2736dea540e99cc940caef51cf2b988705c6d32)
$(call add-radio-file-sha1-checked,radio/xbl.img,87569e5bb09bcced45a8c6a37e61a47506f550a2)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,880d77daa41ac9d7fa93553759e339e4f062a206)

endif
