# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sunfish/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sunfish)

$(call add-radio-file-sha1-checked,radio/abl.img,a7f3c4c236b182a5e8cd6af890a17127f669920c)
$(call add-radio-file-sha1-checked,radio/aop.img,23d06fdd19c8e7e12bf6c0a2ca11c86540a75ec4)
$(call add-radio-file-sha1-checked,radio/devcfg.img,fc75e15e80d05fd97e5485e61e2266076325c710)
$(call add-radio-file-sha1-checked,radio/hyp.img,5b135120df96c2ba9d1da67d49f5b4b5dac1c1fa)
$(call add-radio-file-sha1-checked,radio/keymaster.img,e55b41dc4dfce9567d8cb3e0f4febcf8834cbeb3)
$(call add-radio-file-sha1-checked,radio/modem.img,61d087b16514a71ab0c8d5fe1982de59787534d8)
$(call add-radio-file-sha1-checked,radio/qupfw.img,6bdf862507aa4e75bcbae1a21f815561ccd9a20c)
$(call add-radio-file-sha1-checked,radio/tz.img,208389bd45ee744daf9bbfb11879416e9cfbbb37)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,0a388e724e31b2aa0b52426c5e947bd0e88b7487)
$(call add-radio-file-sha1-checked,radio/xbl.img,a44b3e84943ff13d833ba2768fb9497d094726bb)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,e73e5b4ea9734153bab52143cb1b8f16652b2b8e)

endif
